version: 2
registries:
  pylance-azure-npm-feed:
    type: npm-registry
    url: https://pkgs.dev.azure.com/devdiv/_packaging/Pylance/npm/registry
    token: ${{ secrets.NPM_PRIVATE_REG_TOKEN }}

updates:
  - package-ecosystem: 'npm'
    directory: ''
    registries:
      - pylance-azure-npm-feed
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Build/16.0'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'Build/17.0'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one



# Built with ❤ by [Pipeline Foundation](https://pipeline.foundation)
